# Default configuration for Myrient URLs
# You can add more platforms here as needed!

# EXISTING FLAGS:
# - show_ps3dec: Show PS3 decryption options in GUI
# - show_pkg_split: Show PS3/PSN PKG split options in GUI (*.66600, *.66601, etc.)

ps3:
  tab_name: "PS3 (ISO)"
  url: "https://dl10.myrient.erista.me/files/Redump/Sony - PlayStation 3"
  dkeys: "https://dl10.myrient.erista.me/files/Redump/Sony - PlayStation 3 - Disc Keys TXT/"
  show_ps3dec: true

psn:
  tab_name: "PS3/PSN (PKG)"
  url: "https://dl8.myrient.erista.me/files/No-Intro/Sony%20-%20PlayStation%203%20(PSN)%20(Content)"
  show_pkg_split: true

ps2:
  tab_name: "PS2 (ISO)"  
  url: "https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%202/"

psx:
  tab_name: "PSX (ISO)"
  url: "https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation/"

psp:
  tab_name: "PSP (ISO)"
  url: "https://myrient.erista.me/files/Redump/Sony%20-%20PlayStation%20Portable/"

gamecube:
  tab_name: "GameCube (RVZ)"
  url: "https://myrient.erista.me/files/Redump/Nintendo%20-%20GameCube%20-%20NKit%20RVZ%20[zstd-19-128k]/"

wii:
  tab_name: "Wii (RVZ)"
  url: "https://myrient.erista.me/files/Redump/Nintendo%20-%20Wii%20-%20NKit%20RVZ%20[zstd-19-128k]/"

